### ISSUE TITLE
Issue on Linux with Vagrant Box not setting hostname

### ISSUE THREAD

**Issue by cderenburger** [codeforamerica/ohana-api-dev-box#12]
For future users I had an issue with vagrant during install and running a variety of commands, especially sudo.  My vagrant box would not properly install software, could not run scripts, or rake tests.

PROBLEM
---------------

During initial <code>vagrant up</code>.
```
==> default: Checking for host entries
==> default: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -f
hostnamectl set-hostname 'ohana-api-dev-box'

Stdout from the command:



Stderr from the command:

stdin: is not a tty
bash: line 2: hostnamectl: command not found
```

Subsequently running <code>vagrant halt</code> and then <code>vagrant up</code>.

```
==> default: Checking for host entries
==> default: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -f

Stdout from the command:



Stderr from the command:

sudo: unable to resolve host ohana-api-dev-box
stdin: is not a tty
hostname: Name or service not known
```
When running <code>sudo</code> or a variety of of other commands

```
vagrant@ohana-api-dev-box-64:/media$ sudo reboot
sudo: unable to resolve host ohana-api-dev-box
```
WORKAROUND
---------------
I had to install with the following steps to get my box up and running.
  ```
  $ git clone https://github.com/codeforamerica/ohana-api-dev-box
  $ cd ohana-api-dev-box
  $ vagrant up
  $ vagrant plugin install vagrant-hostsupdater
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostsupdater (0.0.11)'!
  $ vagrant hostsupdater
ran command
  $ vagrant provision
  ```
Provision takes a while to complete, but without <code>vagrant hostsupdater</code> and <code>vagrant provision</code> rvm, bundler, and other packages were failing to install properly.

I have an issue with synced folders not mounting so I also have to do the following:

  1. <code>vagrant halt</code>
  2. Open Virtualbox.
  3. Right-click the 'ohana-api-dev-box_default' machine and select 'Settings'.
  4. In 'Shared Folders' set /vagrant/ohana-api-dev-box to 'Auto-mount'.
  5. Adjust 'System' 'Motherboard' to larger base memory if needed.
  6. <code>vagrant up</code> - restart the vagrant server
  7. <code>vagrant ssh</code> - log into the server
  8. <code>sudo adduser $USER vboxsf</code> - allow user to open shared folders
  9. <code>sudo reboot</code> - reboot
  10. <code>vagrant ssh</code> - log back in
  11. <code>ln -s /media/sf_vagrant/ohana-api/ ohana-api</code> - create shortcut to ohana-api folder in /home
  12. <code>ln -s /media/sf_vagrant/ohana-web-search/ ohana-web-search</code> - create shortcut to ohana-web-search folder in /home

*Note: when shutting down vagrant and restarting I sometimes have the shared folders fail to mount.  Re-open Virtual box, set the folders to 'auto-mount' and from within the vagrant box run <code>sudo reboot</code> to mount the folders.*

With any luck this may help users receiving the hostname errors.

**Comment by monfresh** [comment]
Thanks for the report. I'll try this on my end, but in the meantime, could you answer the following questions please?

- What version of Vagrant are you using?
- What version of VirtualBox are you using?
- What kind of machine are you installing the VM on? (OS, hardware, processor, RAM)

**Comment by monfresh** [comment]
I just tried this with the latest versions of Vagrant and VirtualBox and the VM is being provisioned with all the tools without any issues. Here is what I did:

- `cd` into my local `ohana-api-dev-box` directory
- `git pull` to make sure I have the latest code
- `vagrant destroy` to start from a clean state (note that `vagrant up` will not provision a VM that had already been provisioned. To force it to provision again, you will either need to run `vagrant provision` or `vagrant up --provision`)
- `vagrant up`

**Comment by monfresh** [comment]
The synced folder is working for me as well. I was able to `vagrant ssh` and then `cd /vagrant/ohana-api` and it found it.

Note that if you want folders to sync automatically, i.e. as you add new files locally, you want them to appear in your VM, you will need to edit the Vagrantfile to allow rsync, then run `vagrant rsync-auto` before `vagrant ssh`. Our Wiki article has instructions for [setting up rsync on Windows](https://github.com/codeforamerica/ohana-api-dev-box/wiki/Ohana-API-virtual-machine-installation-guide-for-Windows#speed-up-the-performance-of-the-virtual-machine).

Please let me know if that solves your synced folders issue.

**Comment by cderenburger** [comment]
Vagrant version: 1.7.3
VirtualBox: 5.0.2 r102096
OS: Linux Mint 7.1 x64
CPU: AMD Athlon II X2 3000
MB: Gigabyte MA790X-UD4P
RAM: 8GB DDR2

The synced folder issue I'm thinking is with Virtual Box, probably the guest additions. I tried many versions and I think I stuck with guest additions 4.0.3 as the matching guest addions were causing my XP VM to freeze.

Last night I started from a clean state (building x64 box), did a git pull from the repo. Edited the Vagrantfile to grab the hashicorp/precise64.  Same issue here with the hostname problem.  

Shared folders have always updated for me without rsync just fine, set rsync anyway. Didn't test speed with/without rsync, but it seems sbout the same.

**Comment by cderenburger** [comment]
Found this bug:
 v1.7.3: Setting hostname via hostnamectl without a degradation fails Ubuntu boxes version < 13.04 during the setting hostname step. #5947 https://github.com/mitchellh/vagrant/issues/5947

I will update to 1.7.4 when I get a chance and retest.

**Comment by monfresh** [comment]
Nice find. I ran into a Vagrant issue (can't remember what exactly) on another project that affected a version lower than 1.7.2, and now it looks like 1.7.3 might be causing your hostname issue. Thanks for all the details and sorry you're running into these issues. Windows is usually not used for Ruby development, so we didn't do much testing of the VM setup there. The instructions I wrote for Windows are based on the one chance I had to use my dad's Windows laptop about a year ago.

If you feel like it, please add a Wiki article documenting what you had to do on your particular configuration.

I will also do some research on Docker to see if might be a better solution for Windows users.

**Comment by md5** [comment]
@monfresh Speaking as someone who has Dockerized Ohana previously (using the `boot2docker` VM image on OS X, which is the same thing you'd now use with `docker-machine` on Windows), I don't think it's going to be much help. That being said, I haven't tried getting this Vagrant setup working on any platform, so I may be speaking out of turn despite being intimately familiar with Docker.

**Comment by md5** [comment]
Also, I agree that Vagrant 1.7.4 should fix this issue.

**Comment by monfresh** [comment]
Thanks. I updated the Readme to require 1.7.4 or higher, and I also updated the bootstrap script so that it installs Ruby 2.2.2, which is what ohana-api and ohana-web-search require at the moment.
