### ISSUE TITLE
Add instructions on how to find the rails server on Windows

### ISSUE THREAD

**Issue by amsorribes** [codeforamerica/ohana-api-dev-box#9]
Hi,

I am trying to run the Ohana API locally on a Windows 8.1 machine, and I have followed the instructions on the [Ohana API virtual machine installation guide for Windows](https://github.com/codeforamerica/ohana-api-dev-box/wiki/Ohana-API-virtual-machine-installation-guide-for-Windows) step by step. I am able to get the rails server up and running in the virtual machine:
```
=> Booting Puma
=> Rails 4.2.1 application starting in development on http://localhost:8080
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.11.2 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:8080
```
_However_, when I got to http://localhost:8080 in my web browser I only get back "Server not found". 
If I try to see the virtual machine in the web browser it seems to be working okay, http://127.0.0.1:2222  returns:
```SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1```

Please help me (and others with this issue) access the rails server running in the virtual machine, from Windows!

Thanks!

**Comment by monfresh** [comment]
Thanks for using Ohana API, and thanks for the bug report. I will update the instructions, but in the meantime, you can run the app with `puma -p 8080` instead of `rails s -p 8080`.

**Comment by amsorribes** [comment]
Thank you, that worked!
